#ifndef PLATFORM_COMPAT_H
#define PLATFORM_COMPAT_H

/* Compile-time facts only; this header never allocates or synchronizes. */
typedef enum {
    ENGINE_TARGET_FAMILY_UNKNOWN = 0,
    ENGINE_TARGET_FAMILY_LINUX,
    ENGINE_TARGET_FAMILY_WINDOWS,
    ENGINE_TARGET_FAMILY_MACOS,
    ENGINE_TARGET_FAMILY_IOS,
    ENGINE_TARGET_FAMILY_ANDROID,
    ENGINE_TARGET_FAMILY_HARMONYOS,
} EngineTargetFamily;

typedef enum {
    ENGINE_NET_LOOP_UNKNOWN = 0,
    ENGINE_NET_LOOP_EPOLL,
    ENGINE_NET_LOOP_KQUEUE,
    ENGINE_NET_LOOP_IOCP,
} EngineNetLoop;

typedef enum {
    ENGINE_GRAPHICS_API_NONE = 0,
    ENGINE_GRAPHICS_API_OPENGL,
    ENGINE_GRAPHICS_API_COMPILED,
} EngineGraphicsApiStatus;

typedef enum {
    ENGINE_SURFACE_UNAVAILABLE = 0,
    ENGINE_SURFACE_HOST_NATIVE,
    ENGINE_SURFACE_ANDROID_NATIVE_WINDOW,
} EngineSurfaceStatus;

typedef struct {
    EngineTargetFamily target_family;
    EngineNetLoop net_loop;
    EngineGraphicsApiStatus graphics_api;
    EngineSurfaceStatus surface;
    int requires_host_surface;
} EnginePlatformCompatDescriptor;

#if defined(SIMULATE_MACOS) || defined(ENGINE_PLATFORM_MACOS)
#define ENGINE_PLATFORM_COMPAT_TARGET_FAMILY ENGINE_TARGET_FAMILY_MACOS
#define ENGINE_PLATFORM_COMPAT_NET_LOOP ENGINE_NET_LOOP_KQUEUE
#define ENGINE_PLATFORM_COMPAT_GRAPHICS_API ENGINE_GRAPHICS_API_COMPILED
#define ENGINE_PLATFORM_COMPAT_SURFACE ENGINE_SURFACE_HOST_NATIVE
#define ENGINE_PLATFORM_COMPAT_REQUIRES_HOST_SURFACE 1
#elif defined(SIMULATE_IOS) || defined(ENGINE_PLATFORM_IOS)
#define ENGINE_PLATFORM_COMPAT_TARGET_FAMILY ENGINE_TARGET_FAMILY_IOS
#define ENGINE_PLATFORM_COMPAT_NET_LOOP ENGINE_NET_LOOP_KQUEUE
#define ENGINE_PLATFORM_COMPAT_GRAPHICS_API ENGINE_GRAPHICS_API_COMPILED
#define ENGINE_PLATFORM_COMPAT_SURFACE ENGINE_SURFACE_HOST_NATIVE
#define ENGINE_PLATFORM_COMPAT_REQUIRES_HOST_SURFACE 1
#elif defined(SIMULATE_ANDROID) || defined(ENGINE_PLATFORM_ANDROID)
#define ENGINE_PLATFORM_COMPAT_TARGET_FAMILY ENGINE_TARGET_FAMILY_ANDROID
#define ENGINE_PLATFORM_COMPAT_NET_LOOP ENGINE_NET_LOOP_EPOLL
#if defined(ENGINE_ANDROID_NATIVE_WINDOW)
#define ENGINE_PLATFORM_COMPAT_GRAPHICS_API ENGINE_GRAPHICS_API_COMPILED
#define ENGINE_PLATFORM_COMPAT_SURFACE ENGINE_SURFACE_ANDROID_NATIVE_WINDOW
#else
#define ENGINE_PLATFORM_COMPAT_GRAPHICS_API ENGINE_GRAPHICS_API_NONE
#define ENGINE_PLATFORM_COMPAT_SURFACE ENGINE_SURFACE_UNAVAILABLE
#endif
#define ENGINE_PLATFORM_COMPAT_REQUIRES_HOST_SURFACE 1
#elif defined(SIMULATE_HARMONYOS) || defined(ENGINE_PLATFORM_HARMONYOS)
#define ENGINE_PLATFORM_COMPAT_TARGET_FAMILY ENGINE_TARGET_FAMILY_HARMONYOS
#define ENGINE_PLATFORM_COMPAT_NET_LOOP ENGINE_NET_LOOP_EPOLL
#define ENGINE_PLATFORM_COMPAT_GRAPHICS_API ENGINE_GRAPHICS_API_NONE
#define ENGINE_PLATFORM_COMPAT_SURFACE ENGINE_SURFACE_UNAVAILABLE
#define ENGINE_PLATFORM_COMPAT_REQUIRES_HOST_SURFACE 1
#elif defined(ENGINE_PLATFORM_WINDOWS)
#define ENGINE_PLATFORM_COMPAT_TARGET_FAMILY ENGINE_TARGET_FAMILY_WINDOWS
#define ENGINE_PLATFORM_COMPAT_NET_LOOP ENGINE_NET_LOOP_IOCP
#define ENGINE_PLATFORM_COMPAT_GRAPHICS_API ENGINE_GRAPHICS_API_OPENGL
#define ENGINE_PLATFORM_COMPAT_SURFACE ENGINE_SURFACE_HOST_NATIVE
#define ENGINE_PLATFORM_COMPAT_REQUIRES_HOST_SURFACE 1
#elif defined(ENGINE_PLATFORM_LINUX)
#define ENGINE_PLATFORM_COMPAT_TARGET_FAMILY ENGINE_TARGET_FAMILY_LINUX
#define ENGINE_PLATFORM_COMPAT_NET_LOOP ENGINE_NET_LOOP_EPOLL
#define ENGINE_PLATFORM_COMPAT_GRAPHICS_API ENGINE_GRAPHICS_API_OPENGL
#define ENGINE_PLATFORM_COMPAT_SURFACE ENGINE_SURFACE_HOST_NATIVE
#define ENGINE_PLATFORM_COMPAT_REQUIRES_HOST_SURFACE 1
#else
#define ENGINE_PLATFORM_COMPAT_TARGET_FAMILY ENGINE_TARGET_FAMILY_UNKNOWN
#define ENGINE_PLATFORM_COMPAT_NET_LOOP ENGINE_NET_LOOP_UNKNOWN
#define ENGINE_PLATFORM_COMPAT_GRAPHICS_API ENGINE_GRAPHICS_API_NONE
#define ENGINE_PLATFORM_COMPAT_SURFACE ENGINE_SURFACE_UNAVAILABLE
#define ENGINE_PLATFORM_COMPAT_REQUIRES_HOST_SURFACE 0
#endif

static const EnginePlatformCompatDescriptor ENGINE_PLATFORM_COMPAT = {
    ENGINE_PLATFORM_COMPAT_TARGET_FAMILY,
    ENGINE_PLATFORM_COMPAT_NET_LOOP,
    ENGINE_PLATFORM_COMPAT_GRAPHICS_API,
    ENGINE_PLATFORM_COMPAT_SURFACE,
    ENGINE_PLATFORM_COMPAT_REQUIRES_HOST_SURFACE
};

#endif
