if(NOT DEFINED BENCH OR NOT DEFINED THRESHOLD)
    message(FATAL_ERROR "usage: cmake -DBENCH=... -DTHRESHOLD=... [-DRUNS=3] -P rule_engine_bench_regression.cmake")
endif()
if(NOT DEFINED RUNS)
    set(RUNS 3)
endif()
file(STRINGS "${THRESHOLD}" threshold_lines REGEX "^[A-Za-z0-9_.]+=[0-9]+(\\.[0-9]+)?$")
foreach(line IN LISTS threshold_lines)
    string(REGEX MATCH "^([A-Za-z0-9_]+)\\.([A-Za-z0-9_]+)=([0-9]+(\\.[0-9]+)?)$" matched "${line}")
    set(limit_${CMAKE_MATCH_1}_${CMAKE_MATCH_2} "${CMAKE_MATCH_3}")
endforeach()
math(EXPR last_run "${RUNS} - 1")
foreach(run RANGE 0 ${last_run})
    execute_process(COMMAND "${BENCH}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "benchmark failed on run ${run}: ${error}")
    endif()
    string(REGEX MATCHALL "([A-Za-z0-9_]+) (cold_load|warm_eval) elapsed_seconds=([0-9]+\\.[0-9]+)" records "${output}")
    foreach(record IN LISTS records)
        string(REGEX MATCH "^([A-Za-z0-9_]+) (cold_load|warm_eval) elapsed_seconds=([0-9]+\\.[0-9]+)" matched "${record}")
        set(case_name "${CMAKE_MATCH_1}")
        set(metric "${CMAKE_MATCH_2}")
        set(elapsed "${CMAKE_MATCH_3}")
        if(NOT DEFINED limit_${case_name}_${metric})
            message(FATAL_ERROR "no threshold for ${case_name}.${metric}")
        endif()
        if(elapsed GREATER limit_${case_name}_${metric})
            message(FATAL_ERROR "${case_name}.${metric} ${elapsed}s exceeds ${limit_${case_name}_${metric}}s")
        endif()
        message(STATUS "run=${run} ${case_name}.${metric} seconds=${elapsed} threshold=${limit_${case_name}_${metric}}")
    endforeach()
endforeach()
