#include "test_framework.h"
#include "platform/platform_compat.h"

static void assert_common(void)
{
    ASSERT_TRUE(ENGINE_PLATFORM_COMPAT_TARGET_FAMILY != 0);
    ASSERT_TRUE(ENGINE_PLATFORM_COMPAT_NET_LOOP != 0);
}

TEST(host_descriptor)
{
    assert_common();
#if defined(ENGINE_PLATFORM_LINUX)
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_TARGET_FAMILY, ENGINE_TARGET_FAMILY_LINUX);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_NET_LOOP, ENGINE_NET_LOOP_EPOLL);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_GRAPHICS_API, ENGINE_GRAPHICS_API_OPENGL);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_SURFACE, ENGINE_SURFACE_HOST_NATIVE);
#elif defined(ENGINE_PLATFORM_MACOS)
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_TARGET_FAMILY, ENGINE_TARGET_FAMILY_MACOS);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_NET_LOOP, ENGINE_NET_LOOP_KQUEUE);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_SURFACE, ENGINE_SURFACE_HOST_NATIVE);
#elif defined(ENGINE_PLATFORM_WINDOWS)
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_TARGET_FAMILY, ENGINE_TARGET_FAMILY_WINDOWS);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_NET_LOOP, ENGINE_NET_LOOP_IOCP);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_SURFACE, ENGINE_SURFACE_HOST_NATIVE);
#endif
}

TEST(descriptor_is_compile_time)
{
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT.target_family,
              ENGINE_PLATFORM_COMPAT_TARGET_FAMILY);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT.net_loop, ENGINE_PLATFORM_COMPAT_NET_LOOP);
    ASSERT_TRUE(ENGINE_PLATFORM_COMPAT_TARGET_FAMILY ==
                ENGINE_PLATFORM_COMPAT_TARGET_FAMILY);
    ASSERT_TRUE(ENGINE_PLATFORM_COMPAT_NET_LOOP == ENGINE_PLATFORM_COMPAT_NET_LOOP);
}

int main(void)
{
    RUN_TEST(host_descriptor);
    RUN_TEST(descriptor_is_compile_time);
    printf("\n=== Results: %d passed, %d failed, %d total ===\n",
           g_test_pass, g_test_fail, g_test_count);
    return g_test_fail > 0 ? 1 : 0;
}
