#include "test_framework.h"
#include "platform/platform_compat.h"

TEST(simulated_descriptor)
{
#if defined(SIMULATE_MACOS)
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_TARGET_FAMILY, ENGINE_TARGET_FAMILY_MACOS);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_NET_LOOP, ENGINE_NET_LOOP_KQUEUE);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_SURFACE, ENGINE_SURFACE_HOST_NATIVE);
    ASSERT_TRUE(ENGINE_PLATFORM_COMPAT_REQUIRES_HOST_SURFACE);
#elif defined(SIMULATE_IOS)
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_TARGET_FAMILY, ENGINE_TARGET_FAMILY_IOS);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_NET_LOOP, ENGINE_NET_LOOP_KQUEUE);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_GRAPHICS_API, ENGINE_GRAPHICS_API_COMPILED);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_SURFACE, ENGINE_SURFACE_HOST_NATIVE);
    ASSERT_TRUE(ENGINE_PLATFORM_COMPAT_REQUIRES_HOST_SURFACE);
#elif defined(SIMULATE_ANDROID)
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_TARGET_FAMILY, ENGINE_TARGET_FAMILY_ANDROID);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_NET_LOOP, ENGINE_NET_LOOP_EPOLL);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_SURFACE, ENGINE_SURFACE_UNAVAILABLE);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_GRAPHICS_API, ENGINE_GRAPHICS_API_NONE);
    ASSERT_TRUE(ENGINE_PLATFORM_COMPAT_REQUIRES_HOST_SURFACE);
#elif defined(SIMULATE_HARMONYOS)
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_TARGET_FAMILY, ENGINE_TARGET_FAMILY_HARMONYOS);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_NET_LOOP, ENGINE_NET_LOOP_EPOLL);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_SURFACE, ENGINE_SURFACE_UNAVAILABLE);
    ASSERT_EQ(ENGINE_PLATFORM_COMPAT_GRAPHICS_API, ENGINE_GRAPHICS_API_NONE);
    ASSERT_TRUE(ENGINE_PLATFORM_COMPAT_REQUIRES_HOST_SURFACE);
#else
    ASSERT_TRUE(0);
#endif
}

int main(void)
{
    RUN_TEST(simulated_descriptor);
    printf("\n=== Results: %d passed, %d failed, %d total ===\n",
           g_test_pass, g_test_fail, g_test_count);
    return g_test_fail > 0 ? 1 : 0;
}
