/*
 * IBL (Image Based Lighting) precomputation implementation.
 *
 * Owns three GPU resources used by the Cook-Torrance ambient term:
 *   - BRDF LUT (analytical, no env input required)
 *   - Diffuse irradiance cubemap
 *   - Prefiltered radiance cubemap (split-sum specular)
 *
 * Each resource is generated by a dedicated compute shader.  The compute
 * pipelines are loaded lazily inside ibl_generate so that ibl_init does not
 * fail when the application does not require precomputation.
 *
 * Compute output is written through the RHI image-binding interface: the BRDF
 * LUT via `rhi_cmd_bind_image_texture` (2D) and the environment / irradiance /
 * prefilter cubemaps via `rhi_cmd_bind_image_cubemap_face` (per-face, per-mip).
 * After each set of compute writes the host transitions the cubemap from the
 * compute GENERAL layout to a shader-readable layout with
 * `rhi_cubemap_transition_to_read` so the PBR pass can sample it.
 */

#include <renderer/ibl.h>
#include <core/log.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ===== Helpers ============================================================ */

static char *ibl_read_file(const char *path, usize *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return NULL; }
    long sz = ftell(f);
    if (sz < 0) { fclose(f); return NULL; }
    rewind(f);
    char *buf = (char *)malloc((usize)sz + 1u);
    if (!buf) { fclose(f); return NULL; }
    usize rd = fread(buf, 1, (usize)sz, f);
    buf[rd] = '\0';
    fclose(f);
    if (out_len) *out_len = rd;
    return buf;
}

static RHIPipeline ibl_load_compute(RHIDevice *dev, const char *path) {
    usize len = 0;
    char *src = ibl_read_file(path, &len);
    if (!src) {
        LOG_WARN("IBL: compute shader not found: %s", path);
        return RHI_HANDLE_NULL;
    }
    RHIShader cs = rhi_shader_create_compute(dev, src, len);
    free(src);
    if (!rhi_handle_valid(cs)) {
        LOG_WARN("IBL: compute shader compile failed: %s", path);
        return RHI_HANDLE_NULL;
    }
    RHIPipelineDesc desc = {0};
    desc.frag = cs;
    desc.is_compute = true;
    desc.uses_textures = true;
    desc.uses_storage = true;
    RHIPipeline pipe = rhi_pipeline_create(dev, &desc);
    rhi_shader_destroy(dev, cs);
    if (!rhi_handle_valid(pipe)) {
        LOG_WARN("IBL: compute pipeline create failed: %s", path);
    }
    return pipe;
}

/* Create an HDR (RGBA16F) cubemap with `mips` mip levels.  Faces start
 * undefined/black; compute passes write the real contents and the host
 * transitions the image to a shader-readable layout afterwards. */
static RHICubemap ibl_create_hdr_cube(RHIDevice *dev, u32 size, u32 mips) {
    RHICubemapDesc d = {0};
    d.size       = size;
    d.format     = RHI_FORMAT_R16G16B16A16_SFLOAT;
    d.mip_levels = mips;
    for (int i = 0; i < 6; ++i) d.faces[i] = NULL;
    return rhi_cubemap_create(dev, &d);
}

/* ===== Public API ========================================================= */

void ibl_init(IBLSystem *sys, RHIDevice *dev) {
    memset(sys, 0, sizeof(*sys));
    sys->device = dev;
    sys->brdf_lut             = RHI_HANDLE_NULL;
    sys->env_map              = RHI_HANDLE_NULL;
    sys->irradiance_map       = RHI_HANDLE_NULL;
    sys->prefilter_map        = RHI_HANDLE_NULL;
    sys->cubemap_sampler      = RHI_HANDLE_NULL;
    sys->sky_capture_pipeline = RHI_HANDLE_NULL;
    sys->brdf_lut_pipeline    = RHI_HANDLE_NULL;
    sys->irradiance_pipeline  = RHI_HANDLE_NULL;
    sys->prefilter_pipeline   = RHI_HANDLE_NULL;
    sys->ready = false;

    if (!dev) {
        LOG_WARN("IBL: ibl_init called with NULL device");
        return;
    }

    /* ---- BRDF LUT ------------------------------------------------------- */
    /* The RHI exposes RGBA16F but not RG16F; use RGBA16F and ignore B/A. */
    {
        RHITextureDesc d = {0};
        d.width      = IBL_BRDF_LUT_SIZE;
        d.height     = IBL_BRDF_LUT_SIZE;
        d.format     = RHI_FORMAT_R16G16B16A16_SFLOAT;
        d.mip_levels = 1u;
        d.data       = NULL;
        sys->brdf_lut = rhi_texture_create(dev, &d);
        if (!rhi_handle_valid(sys->brdf_lut)) {
            LOG_WARN("IBL: failed to create BRDF LUT texture");
        }
    }

    /* ---- Environment, irradiance and prefilter cubemaps (all RGBA16F) --- */
    sys->env_map = ibl_create_hdr_cube(dev, IBL_ENV_SIZE, 1u);
    if (!rhi_handle_valid(sys->env_map))
        LOG_WARN("IBL: failed to create environment cubemap");

    sys->irradiance_map = ibl_create_hdr_cube(dev, IBL_IRRADIANCE_SIZE, 1u);
    if (!rhi_handle_valid(sys->irradiance_map))
        LOG_WARN("IBL: failed to create irradiance cubemap");

    sys->prefilter_map = ibl_create_hdr_cube(dev, IBL_PREFILTER_SIZE, IBL_PREFILTER_MIP_COUNT);
    if (!rhi_handle_valid(sys->prefilter_map))
        LOG_WARN("IBL: failed to create prefilter cubemap");

    /* ---- Cubemap sampler (for reading env_map in compute) --------------- */
    {
        RHISamplerDesc sd = {0};
        sd.min_filter = RHI_FILTER_LINEAR;
        sd.mag_filter = RHI_FILTER_LINEAR;
        sd.wrap_u = RHI_WRAP_CLAMP_TO_EDGE;
        sd.wrap_v = RHI_WRAP_CLAMP_TO_EDGE;
        sd.wrap_w = RHI_WRAP_CLAMP_TO_EDGE;
        sys->cubemap_sampler = rhi_sampler_create(dev, &sd);
    }
}

void ibl_destroy(IBLSystem *sys, RHIDevice *dev) {
    if (!sys || !dev) return;

    if (rhi_handle_valid(sys->sky_capture_pipeline)) {
        rhi_pipeline_destroy(dev, sys->sky_capture_pipeline);
        sys->sky_capture_pipeline = RHI_HANDLE_NULL;
    }
    if (rhi_handle_valid(sys->brdf_lut_pipeline)) {
        rhi_pipeline_destroy(dev, sys->brdf_lut_pipeline);
        sys->brdf_lut_pipeline = RHI_HANDLE_NULL;
    }
    if (rhi_handle_valid(sys->irradiance_pipeline)) {
        rhi_pipeline_destroy(dev, sys->irradiance_pipeline);
        sys->irradiance_pipeline = RHI_HANDLE_NULL;
    }
    if (rhi_handle_valid(sys->prefilter_pipeline)) {
        rhi_pipeline_destroy(dev, sys->prefilter_pipeline);
        sys->prefilter_pipeline = RHI_HANDLE_NULL;
    }

    if (rhi_handle_valid(sys->brdf_lut)) {
        rhi_texture_destroy(dev, sys->brdf_lut);
        sys->brdf_lut = RHI_HANDLE_NULL;
    }
    if (rhi_handle_valid(sys->env_map)) {
        rhi_cubemap_destroy(dev, sys->env_map);
        sys->env_map = RHI_HANDLE_NULL;
    }
    if (rhi_handle_valid(sys->irradiance_map)) {
        rhi_cubemap_destroy(dev, sys->irradiance_map);
        sys->irradiance_map = RHI_HANDLE_NULL;
    }
    if (rhi_handle_valid(sys->prefilter_map)) {
        rhi_cubemap_destroy(dev, sys->prefilter_map);
        sys->prefilter_map = RHI_HANDLE_NULL;
    }

    if (rhi_handle_valid(sys->cubemap_sampler)) {
        rhi_sampler_destroy(dev, sys->cubemap_sampler);
        sys->cubemap_sampler = RHI_HANDLE_NULL;
    }

    sys->ready  = false;
    sys->device = NULL;
}

void ibl_capture_env_sky(IBLSystem *sys, RHIDevice *dev,
                         const f32 sun_dir[3], const f32 sun_color[3]) {
    if (!sys || !dev || !rhi_handle_valid(sys->env_map)) return;

    if (!rhi_handle_valid(sys->sky_capture_pipeline)) {
        sys->sky_capture_pipeline = ibl_load_compute(dev, "shaders/sky_to_cube.comp");
    }
    if (!rhi_handle_valid(sys->sky_capture_pipeline)) {
        LOG_WARN("IBL: sky capture pipeline unavailable; env map left black");
        return;
    }

    f32 dir[3]   = { 0.0f, 1.0f, 0.0f };
    f32 color[3] = { 1.0f, 1.0f, 1.0f };
    if (sun_dir)   { dir[0] = sun_dir[0]; dir[1] = sun_dir[1]; dir[2] = sun_dir[2]; }
    if (sun_color) { color[0] = sun_color[0]; color[1] = sun_color[1]; color[2] = sun_color[2]; }

    i32 loc_face = rhi_pipeline_get_uniform_location(dev, sys->sky_capture_pipeline, "u_face");
    i32 loc_size = rhi_pipeline_get_uniform_location(dev, sys->sky_capture_pipeline, "u_face_size");
    i32 loc_sdir = rhi_pipeline_get_uniform_location(dev, sys->sky_capture_pipeline, "u_sun_dir");
    i32 loc_scol = rhi_pipeline_get_uniform_location(dev, sys->sky_capture_pipeline, "u_sun_color");

    const u32 groups = (IBL_ENV_SIZE + 15u) / 16u;
    for (u32 face = 0u; face < 6u; ++face) {
        RHICmdBuffer *cmd = rhi_frame_begin(dev);
        if (!cmd) break;
        rhi_cmd_bind_pipeline(cmd, sys->sky_capture_pipeline);
        rhi_cmd_bind_image_cubemap_face(cmd, sys->env_map, face, 0u, 0u, true);
        if (loc_face >= 0) rhi_cmd_set_uniform_i32(cmd, loc_face, (i32)face);
        if (loc_size >= 0) rhi_cmd_set_uniform_i32(cmd, loc_size, (i32)IBL_ENV_SIZE);
        if (loc_sdir >= 0) rhi_cmd_set_uniform_vec3(cmd, loc_sdir, dir[0], dir[1], dir[2]);
        if (loc_scol >= 0) rhi_cmd_set_uniform_vec3(cmd, loc_scol, color[0], color[1], color[2]);
        rhi_cmd_dispatch(cmd, groups, groups, 1u);
        rhi_cmd_memory_barrier(cmd);
        rhi_frame_end(dev);
        rhi_present(dev);
    }

    /* Compute wrote faces in GENERAL layout; make them sampleable. */
    rhi_cubemap_transition_to_read(dev, sys->env_map);
}

void ibl_generate(IBLSystem *sys, RHIDevice *dev, RHICubemap env_map) {
    if (!sys || !dev) return;

    /* Lazy compute pipeline creation. The BRDF LUT needs no env input and is
     * always built. The irradiance/prefilter convolution pipelines consume the
     * environment cubemap, so only build them when an env map is supplied —
     * this avoids creating (and validating) unused pipelines on the common
     * "BRDF-only" path. */
    if (!rhi_handle_valid(sys->brdf_lut_pipeline)) {
        sys->brdf_lut_pipeline = ibl_load_compute(dev, "shaders/brdf_lut.comp");
    }
    if (rhi_handle_valid(env_map)) {
        if (!rhi_handle_valid(sys->irradiance_pipeline)) {
            sys->irradiance_pipeline = ibl_load_compute(dev, "shaders/irradiance_env.comp");
        }
        if (!rhi_handle_valid(sys->prefilter_pipeline)) {
            sys->prefilter_pipeline = ibl_load_compute(dev, "shaders/prefilter_env.comp");
        }
    }

    /* ---- Pass 1: BRDF LUT ------------------------------------------------
     * Pure analytic integration of GGX importance sampling; no env input.
     * 16x16 workgroups -> 32x32 dispatch for a 512x512 LUT.            */
    if (rhi_handle_valid(sys->brdf_lut_pipeline) && rhi_handle_valid(sys->brdf_lut)) {
        RHICmdBuffer *cmd = rhi_frame_begin(dev);
        if (cmd) {
            rhi_cmd_bind_pipeline(cmd, sys->brdf_lut_pipeline);
            rhi_cmd_bind_image_texture(cmd, sys->brdf_lut, 0u, 0u, true);
            const u32 groups = IBL_BRDF_LUT_SIZE / 16u;
            rhi_cmd_dispatch(cmd, groups, groups, 1u);
            rhi_cmd_memory_barrier(cmd);
            rhi_frame_end(dev);
            /* rhi_frame_begin acquires a swapchain image; present to recycle it
             * so the many precompute frames below don't exhaust the swapchain. */
            rhi_present(dev);
            /* The LUT was written as a storage image (GENERAL); transition it to
             * a shader-readable layout so the PBR pass can sample it. */
            rhi_texture_transition_to_read(dev, sys->brdf_lut);
        }
    }

    /* Cache uniform locations for irradiance and prefilter pipelines. */
    i32 loc_face_irr  = -1, loc_face_size  = -1;
    i32 loc_face_pref  = -1, loc_mip_size   = -1, loc_roughness = -1;
    if (rhi_handle_valid(sys->irradiance_pipeline)) {
        loc_face_irr  = rhi_pipeline_get_uniform_location(dev, sys->irradiance_pipeline, "u_face");
        loc_face_size = rhi_pipeline_get_uniform_location(dev, sys->irradiance_pipeline, "u_face_size");
    }
    if (rhi_handle_valid(sys->prefilter_pipeline)) {
        loc_face_pref  = rhi_pipeline_get_uniform_location(dev, sys->prefilter_pipeline, "u_face");
        loc_mip_size   = rhi_pipeline_get_uniform_location(dev, sys->prefilter_pipeline, "u_mip_size");
        loc_roughness  = rhi_pipeline_get_uniform_location(dev, sys->prefilter_pipeline, "u_roughness");
    }

    /* ---- Pass 2: irradiance convolution ---------------------------------
     * Per-face dispatch with cosine-weighted hemisphere integration.
     * 16x16 workgroups -> 4x4 dispatch for 64x64 output.              */
    if (rhi_handle_valid(sys->irradiance_pipeline) &&
        rhi_handle_valid(sys->irradiance_map) &&
        rhi_handle_valid(env_map)) {
        const u32 irr_groups = IBL_IRRADIANCE_SIZE / 16u;
        for (u32 face = 0u; face < 6u; ++face) {
            RHICmdBuffer *cmd = rhi_frame_begin(dev);
            if (!cmd) break;
            rhi_cmd_bind_pipeline(cmd, sys->irradiance_pipeline);
            /* binding 0: output (storage image, single face, mip 0) */
            rhi_cmd_bind_image_cubemap_face(cmd, sys->irradiance_map, face, 0u, 0u, true);
            /* binding 1: input (samplerCube env map) */
            rhi_cmd_bind_cubemap_sampler(cmd, env_map, sys->cubemap_sampler, 1u);
            if (loc_face_irr >= 0)  rhi_cmd_set_uniform_i32(cmd, loc_face_irr, (i32)face);
            if (loc_face_size >= 0) rhi_cmd_set_uniform_i32(cmd, loc_face_size, (i32)IBL_IRRADIANCE_SIZE);
            rhi_cmd_dispatch(cmd, irr_groups, irr_groups, 1u);
            rhi_cmd_memory_barrier(cmd);
            rhi_frame_end(dev);
            rhi_present(dev);
        }
        /* Compute wrote faces in GENERAL layout; make them sampleable. */
        rhi_cubemap_transition_to_read(dev, sys->irradiance_map);
    }

    /* ---- Pass 3: prefiltered radiance, per mip & face -------------------
     * Importance-sampled GGX pre-integration.  Mip index encodes roughness.
     * 16x16 workgroups -> dispatch = ceil(mip_size/16).              */
    if (rhi_handle_valid(sys->prefilter_pipeline) &&
        rhi_handle_valid(sys->prefilter_map) &&
        rhi_handle_valid(env_map)) {
        for (u32 mip = 0u; mip < IBL_PREFILTER_MIP_COUNT; ++mip) {
            u32 mip_size = IBL_PREFILTER_SIZE >> mip;
            if (mip_size == 0u) mip_size = 1u;
            u32 groups = (mip_size + 15u) / 16u;
            f32 roughness = (f32)mip / (f32)(IBL_PREFILTER_MIP_COUNT - 1u);
            for (u32 face = 0u; face < 6u; ++face) {
                RHICmdBuffer *cmd = rhi_frame_begin(dev);
                if (!cmd) break;
                rhi_cmd_bind_pipeline(cmd, sys->prefilter_pipeline);
                /* binding 0: output storage image = this face at this mip. */
                rhi_cmd_bind_image_cubemap_face(cmd, sys->prefilter_map, face, mip, 0u, true);
                rhi_cmd_bind_cubemap_sampler(cmd, env_map, sys->cubemap_sampler, 1u);
                if (loc_roughness >= 0) rhi_cmd_set_uniform_f32(cmd, loc_roughness, roughness);
                if (loc_face_pref >= 0) rhi_cmd_set_uniform_i32(cmd, loc_face_pref, (i32)face);
                if (loc_mip_size >= 0)  rhi_cmd_set_uniform_i32(cmd, loc_mip_size, (i32)mip_size);
                rhi_cmd_dispatch(cmd, groups, groups, 1u);
                rhi_cmd_memory_barrier(cmd);
                rhi_frame_end(dev);
                rhi_present(dev);
            }
        }
        /* Compute wrote all face/mip subresources in GENERAL layout. */
        rhi_cubemap_transition_to_read(dev, sys->prefilter_map);
    }

    /* R351: textures alone are not success — env convolution needs sampler +
     * pipelines (otherwise ready=true with unbound cubemap reads). */
    bool ok = rhi_handle_valid(sys->brdf_lut)
           && rhi_handle_valid(sys->irradiance_map)
           && rhi_handle_valid(sys->prefilter_map)
           && rhi_handle_valid(sys->brdf_lut_pipeline);
    if (ok && rhi_handle_valid(env_map)) {
        if (!rhi_handle_valid(sys->cubemap_sampler) ||
            !rhi_handle_valid(sys->irradiance_pipeline) ||
            !rhi_handle_valid(sys->prefilter_pipeline)) {
            LOG_WARN("IBL: env convolution resources incomplete");
            ok = false;
        }
    }
    sys->ready = ok;
}
